build:
  image: golang:1.6-alpine
  commands:
    - apk add --update git
    - go get
    - go build
    - go test

publish:
  docker:
    registry: registry.aguirre.io:5000
    repo: goreportcard
    tag: latest
